version: "2"
services:
  web:
    build: ./client
    volumes:
      - ./client/dist:/usr/www
    ports:
      - "80:80"
  server:
    build: ./server
    volumes:
      - ./server:/usr/nodedice
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./mongodb/db:/data/db
    ports:
      - "127.0.0.1:27017:27017"